### ISSUE TITLE
grav.CRITICAL: Cannot load blueprint blueprints://flex-objects/pages.yaml: Failed to read pages:

### ISSUE THREAD

**Issue by gibumpark** [trilbymedia/grav-plugin-flex-objects#135]
grav.CRITICAL: Cannot load blueprint blueprints://flex-objects/pages.yaml: Failed to read pages: is_file() expects parameter 1 to be a valid path, string given - Trace: #0 /Users/gibum/Sites/macweb/system/src/Grav/Framework/Flex/FlexDirectory.php(778): RocketTheme\Toolbox\Blueprints\BlueprintForm->load(NULL) #1 /Users/gibum/Sites/macweb/system/src/Grav/Framework/Flex/FlexDirectory.php(156): Grav\Framework\Flex\FlexDirectory->getBlueprintInternal() #2 /Users/gibum/Sites/macweb/user/plugins/flex-objects/classes/Admin/AdminController.php(1751): Grav\Framework\Flex\FlexDirectory->getConfig('admin') #3 /Users/gibum/Sites/macweb/user/plugins/flex-objects/classes/Admin/AdminController.php(1263): Grav\Plugin\FlexObjects\Admin\AdminController->getAdminRoutes() #4 /Users/gibum/Sites/macweb/user/plugins/flex-objects/flex-objects.php(242): Grav\Plugin\FlexObjects\Admin\AdminController->__construct() #5 /Users/gibum/Sites/macweb/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\FlexObjectsPlugin->onThemeInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onThemeInitiali...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #6 /Users/gibum/Sites/macweb/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onThemeInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #7 /Users/gibum/Sites/macweb/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'onThemeInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #8 /Users/gibum/Sites/macweb/system/src/Grav/Common/Grav.php(556): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(RocketTheme\Toolbox\Event\Event), 'onThemeInitiali...') #9 /Users/gibum/Sites/macweb/system/src/Grav/Common/Themes.php(112): Grav\Common\Grav->fireEvent('onThemeInitiali...') #10 /Users/gibum/Sites/macweb/user/plugins/admin/classes/plugin/Themes.php(18): Grav\Common\Themes->initTheme() #11 /Users/gibum/Sites/macweb/system/src/Grav/Common/Processors/ThemesProcessor.php(35): Grav\Plugin\Admin\Themes->init() #12 /Users/gibum/Sites/macweb/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #13 /Users/gibum/Sites/macweb/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #14 /Users/gibum/Sites/macweb/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #15 /Users/gibum/Sites/macweb/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #16 /Users/gibum/Sites/macweb/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #17 /Users/gibum/Sites/macweb/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /Users/gibum/Sites/macweb/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #19 /Users/gibum/Sites/macweb/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile(Object(Closure)) #20 /Users/gibum/Sites/macweb/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #21 /Users/gibum/Sites/macweb/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /Users/gibum/Sites/macweb/system/src/Grav/Common/Grav.php(295): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /Users/gibum/Sites/macweb/index.php(58): Grav\Common\Grav->process() #24 {main} [] []

**Comment by mahagr** [comment]
This is the first time I've seen an issue like this. The file should be located in `user/plugins/flex-objects/blueprints/flex-objects/pages.yaml`.
