### ISSUE TITLE
Flex Objects getRoute() error when running Grav scheduler

### ISSUE THREAD

**Issue by superhu4** [trilbymedia/grav-plugin-flex-objects#151]
After updating plugins, I now get the following error when `bin/grav` scheduler runs:

```
PHP Fatal error:  Uncaught Error: Call to a member function getRoute() on null in /home/example.com/gravsite/user/plugins/flex-objects/flex-objects.php:293
Stack trace:
#0 /home/example.com/gravsite/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\FlexObjectsPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#1 /home/example.com/gravsite/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event))
#2 /home/example.com/gravsite/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event))
#3 /home/example.com/gravsite/system/src/Grav/Common/Grav.php in /home/example.com/gravsite/user/plugins/flex-objects/flex-objects.php on line 293
```

Any input is welcome!

**Comment by mahagr** [comment]
Please try with above fix. :)
